version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/tmp
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Clone and Build RSKj (Master)
          command: |
                    GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
                    git clone git@github.com:rsksmart/rskj.git ~/rsksmart/rskj-master
                    cd ~/rsksmart/rskj-master/
                    ./configure.sh
                    ./gradlew clean build -x test
                    cp ~/rsksmart/rskj-master/rskj-core/build/libs/rskj-core-2.2.0-SNAPSHOT-all.jar ~/tmp
      - run:
          name: Clone and Build RSKj  (PAPYRUS-2.1.0)
          command: |
                    GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
                    git clone -b PAPYRUS-2.1.0 git@github.com:rsksmart/rskj.git ~/rsksmart/rskj-PAPYRUS-2.1.0
                    cd ~/rsksmart/rskj-PAPYRUS-2.1.0/
                    ./configure.sh
                    ./gradlew clean build -x test
                    cp ~/rsksmart/rskj-PAPYRUS-2.1.0/rskj-core/build/libs/rskj-core-2.1.0-PAPYRUS-all.jar ~/tmp
      - run:
          name: Execute Migration Tests
          command: |
                    cd ~/tmp
                    sh migration-tests/test.sh
      - run:
          name: Execute Truffle Tests
          command: |
                    cd ~/tmp
                    sh truffle-tests/test.sh


